# Generated by Django 6.0.4 on 2026-04-21 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VaultLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=20)),
                ('instagram_handle', models.CharField(blank=True, max_length=50, null=True)),
                ('backup_contact', models.CharField(max_length=20)),
                ('plan_years', models.IntegerField(choices=[(3, '3 Years'), (5, '5 Years')])),
                ('letter_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
