# Generated by Django 6.0.4 on 2026-04-21 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaultletter',
            name='letter_content',
        ),
    ]
