# Generated by Django 6.0.4 on 2026-04-21 22:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_remove_vaultletter_letter_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaultletter',
            name='batch',
            field=models.TextField(choices=[('32', '32'), ('33', '33'), ('34', '34'), ('35', '35')], default=django.utils.timezone.now, verbose_name='Batch'),
            preserve_default=False,
        ),
    ]
