# Generated by Django 6.0.4 on 2026-04-21 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0003_vaultletter_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaultletter',
            name='name',
        ),
        migrations.AlterField(
            model_name='vaultletter',
            name='batch',
            field=models.IntegerField(choices=[(32, 'Batch 32'), (33, 'Batch 33'), (34, 'Batch 34'), (35, 'Batch 35')]),
        ),
    ]
