# Generated by Django 6.0.4 on 2026-04-21 22:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0004_remove_vaultletter_name_alter_vaultletter_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaultletter',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
