# Generated by Django 6.0.4 on 2026-04-22 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0005_vaultletter_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaultletter',
            name='backup_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
